### ISSUE TITLE
Config webpack for production mode

### ISSUE THREAD

**Issue by Melanitski** [Rademade/hackathon-machine#36]
- Need correct URL
- Remove hardcode / Add ENV parameters

**Comment by theHellDog** [comment]
лучше по примеру https://github.com/Producters/docker-node-react-starter/tree/master/frontend

**Comment by 95kach** [comment]
@Melanitski , @theHellDog 
Порефакторил - посмотрите пожалуйста [этот PR](https://github.com/Rademade/hackathon-machine/pull/37)
