### ISSUE TITLE
Rounding rating to hundredths

### ISSUE THREAD

**Issue by Melanitski** [Rademade/hackathon-machine#49]
<img width="508" alt="screen shot 2017-05-23 at 12 59 10 pm" src="https://cloud.githubusercontent.com/assets/509124/26349183/b9405daa-3fb7-11e7-81d1-1384b263127f.png">

**Comment by 95kach** [comment]
This bug was fixed previously
[There you can check it.](https://github.com/Rademade/hackathon-machine/blob/master/frontend/src/app/containers/topics/Index.jsx)
Use:
```
Cntr + F
Math.round(topic.average_vote * 100) / 100
```

@Melanitski 

Hi! Vlad, I just want to ask you 2 questions.

1) Who is QA on this project?
2) Who can close the issue?

**Comment by Melanitski** [comment]
@95kach thanks you for clarifying
