### ISSUE TITLE
we need backend for /sign_up

### ISSUE THREAD

**Issue by 95kach** [Rademade/hackathon-machine#55]
In this PR
https://github.com/Rademade/hackathon-machine/pull/54
I added /sign_up form

And users can create your account using this form, not using "curl request from terminal"

Hi, we need your help.
@robobee

**Comment by robobee** [comment]
@95kach , можемо ще додати name на форму sign_up? Бо у нас наче немає ніде редагування профілю. Нехай на бек приходить json в форматі: {"full_name":"name","password":"password","email":"email@example.com"}
А адресу ендпоінту я зміню на твою.

**Comment by 95kach** [comment]
У нас є редагування спікера.

@robobee Дякую. Тестив бек для реєстрації, робить.
